meta_product_name: "casadosnoivos.online"
meta_title: "CASA DOS NOIVOS - Site de casamento"
meta_description: "Crie um site de casamento personalizado e compartilhe com seus convidados. Faça a lista de presentes, confirme presença e muito mais."
meta_image: "" # should exist in `app/assets/images/`
